# Generated by Django 4.1 on 2023-09-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChoiceTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recode", models.IntegerField()),
                ("choiceTextEnglish", models.TextField(blank=True, null=True)),
                ("choiceTextFrench", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questionType", models.CharField(max_length=30)),
                ("questionName", models.CharField(max_length=30)),
                ("questionTextEnglish", models.TextField()),
                ("questionTextFrench", models.TextField()),
                ("questionTheme", models.CharField(max_length=30)),
                ("questionLabel", models.CharField(max_length=30)),
                ("jsonKey", models.TextField()),
                (
                    "parentQuestionID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InteractiveDB.questiontable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualtricsSurveyID", models.CharField(max_length=30)),
                ("releaseDate", models.DateField()),
                ("fetchedDate", models.DateField(blank=True, null=True)),
                ("surveyTheme", models.CharField(max_length=30)),
                ("surveysubThemeEnglish", models.CharField(max_length=150)),
                ("surveysubThemeFrench", models.CharField(max_length=150)),
                ("surveyWeek", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("externalDataReference", models.CharField(max_length=15)),
                ("province", models.CharField(max_length=2)),
                ("size", models.CharField(max_length=2)),
                ("hrtype", models.CharField(default="VO", max_length=2)),
                ("languagePreference", models.CharField(default="EN", max_length=2)),
                ("designation", models.CharField(max_length=3)),
                ("locationPolygon", models.CharField(max_length=16)),
                ("urbanRural", models.CharField(max_length=2)),
                ("dateFounded", models.DateField(blank=True, null=True)),
                ("age", models.TextField()),
                ("domain", models.TextField()),
                ("subDomain", models.TextField()),
                ("subSample", models.TextField()),
                ("jobTitle", models.TextField()),
                ("region", models.TextField()),
                ("expenditure", models.TextField(default="XS")),
            ],
        ),
        migrations.CreateModel(
            name="UserResponseTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answerTextOriginal", models.TextField(max_length=4096, null=True)),
                ("answerTextEnglish", models.TextField(max_length=4096, null=True)),
                ("answerTextFrench", models.TextField(max_length=4096, null=True)),
                ("answerValue", models.TextField(null=True)),
                (
                    "choiceID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InteractiveDB.choicetable",
                    ),
                ),
                (
                    "questionID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InteractiveDB.questiontable",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="InteractiveDB.usertable",
                    ),
                ),
            ],
            options={
                "ordering": ("questionID",),
            },
        ),
        migrations.AddField(
            model_name="questiontable",
            name="surveyID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="InteractiveDB.surveytable",
            ),
        ),
        migrations.AddField(
            model_name="choicetable",
            name="questionID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="InteractiveDB.questiontable",
            ),
        ),
    ]
