# Generated by Django 4.1 on 2023-05-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractiveDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponsetable',
            name='answerTextOriginal',
            field=models.TextField(max_length=4096, null=True),
        ),
    ]
