# Generated by Django 4.1 on 2023-04-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractiveDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='domain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='jobTitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='subDomain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='subSample',
            field=models.TextField(),
        ),
    ]
